[project]
name = "qbi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "braindecode>=0.8.1",
    "ipykernel>=6.29.5",
    "mne>=1.9.0",
    "numpy>=2.2.3",
]